"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Dashboard;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_router_dom_1 = require("react-router-dom");
const appStore_1 = require("../store/appStore");
const lucide_react_1 = require("lucide-react");
function Dashboard() {
    const schoolProfile = (0, appStore_1.useAppStore)((s) => s.schoolProfile);
    const workbook = (0, appStore_1.useAppStore)((s) => s.workbook);
    const students = (0, appStore_1.useAppStore)((s) => s.students);
    const validation = (0, appStore_1.useAppStore)((s) => s.validation);
    const gen = (0, appStore_1.useAppStore)((s) => s.generation);
    const schoolReady = Boolean(schoolProfile.schoolName && schoolProfile.academicSession && schoolProfile.examTerm);
    const dataReady = students.length > 0;
    const validationReady = validation !== null;
    const generationRan = gen.status !== 'idle';
    const quickActions = [
        { to: '/school-profile', label: 'Set up School Profile', icon: lucide_react_1.GraduationCap, desc: 'Name, logo, signatures, session', done: schoolReady },
        { to: '/import', label: 'Import Students Excel', icon: lucide_react_1.Upload, desc: 'Upload .xlsx / .xls / .csv, map columns', done: dataReady },
        { to: '/template', label: 'Preview Report Template', icon: lucide_react_1.FileText, desc: 'See how the report card looks', done: dataReady },
        { to: '/generate', label: 'Generate & Download', icon: lucide_react_1.Printer, desc: 'PDF per student + ZIP bundle', done: generationRan && gen.status === 'complete' },
    ];
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsxs)("section", { className: "card", children: [(0, jsx_runtime_1.jsxs)("div", { className: "card-header", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-lg font-semibold text-ink-900", children: "Welcome to ReportCard Studio" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-ink-500 mt-1", children: "Excel In. Professional Report Cards Out." })] }), (0, jsx_runtime_1.jsx)("div", { className: "card-body", children: (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-ink-700 leading-relaxed", children: "Upload a student Excel sheet, map your columns to dynamic subjects, validate every record, then generate an individual PDF report card for every student \u2014 packaged automatically into a single ZIP." }) })] }), (0, jsx_runtime_1.jsxs)("section", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4", children: [(0, jsx_runtime_1.jsx)(StatCard, { label: "Students Loaded", value: students.length || '—', sub: workbook ? workbook.fileName : 'No file uploaded yet', tone: students.length ? 'brand' : 'neutral' }), (0, jsx_runtime_1.jsx)(StatCard, { label: "Validation", value: validationReady ? (validation?.isValid ? 'PASSED' : 'ISSUES') : 'Not run', sub: validationReady ? `${validation?.errorCount ?? 0} errors · ${validation?.warningCount ?? 0} warnings` : 'Validate after import', tone: !validationReady ? 'neutral' : validation?.isValid ? 'success' : 'error' }), (0, jsx_runtime_1.jsx)(StatCard, { label: "Dynamic Subjects", value: students[0]?.subjects.length ?? 0, sub: students[0]?.subjects.map((s) => s.name).join(', ') || 'Detected from Excel mapping', tone: "brand" }), (0, jsx_runtime_1.jsx)(StatCard, { label: "Last Generation", value: !generationRan
                            ? 'Not run'
                            : gen.status === 'running'
                                ? 'In progress...'
                                : gen.status === 'complete'
                                    ? 'Complete'
                                    : 'Halted', sub: generationRan ? `${gen.completed} done · ${gen.failed} failed` : 'Run after validation passes', tone: gen.status === 'complete' && gen.failed === 0 ? 'success' : gen.failed > 0 ? 'error' : 'neutral' })] }), (0, jsx_runtime_1.jsxs)("section", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-sm font-semibold text-ink-800 mb-3", children: "Get Started" }), (0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: quickActions.map((a, i) => {
                            const Icon = a.icon;
                            return ((0, jsx_runtime_1.jsx)(react_router_dom_1.Link, { to: a.to, className: "card hover:border-brand-300 transition-colors", children: (0, jsx_runtime_1.jsxs)("div", { className: "card-body flex items-start gap-4", children: [(0, jsx_runtime_1.jsx)("div", { className: `h-10 w-10 rounded-lg flex items-center justify-center shrink-0 ${a.done ? 'bg-emerald-50 text-emerald-600' : 'bg-brand-50 text-brand-600'}`, children: a.done ? (0, jsx_runtime_1.jsx)(lucide_react_1.CheckCircle2, { className: "h-5 w-5" }) : (0, jsx_runtime_1.jsx)(Icon, { className: "h-5 w-5" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "flex-1 min-w-0", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex items-center gap-2", children: (0, jsx_runtime_1.jsxs)("span", { className: "text-xs font-bold text-ink-500", children: ["STEP ", i + 1] }) }), (0, jsx_runtime_1.jsx)("h4", { className: "font-semibold text-ink-900 mt-0.5", children: a.label }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-ink-500 mt-0.5", children: a.desc })] }), (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { className: "h-4 w-4 text-ink-400 shrink-0 mt-2" })] }) }, a.to));
                        }) })] }), (0, jsx_runtime_1.jsxs)("section", { className: "grid grid-cols-1 lg:grid-cols-3 gap-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "card lg:col-span-2", children: [(0, jsx_runtime_1.jsxs)("div", { className: "card-header flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertCircle, { className: "h-4 w-4 text-ink-500" }), (0, jsx_runtime_1.jsx)("h3", { className: "font-semibold text-ink-900", children: "How does it work?" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "card-body text-sm text-ink-700 space-y-2 leading-relaxed", children: [(0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("span", { className: "font-semibold", children: "1. School Profile:" }), " Fill in your school name, address, upload logo and signatures. Saved locally in your browser."] }), (0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("span", { className: "font-semibold", children: "2. Import Students:" }), " Drop your Excel/CSV file. Columns are auto-mapped to name, roll no, parents, attendance, and ", (0, jsx_runtime_1.jsx)("strong", { children: "dynamic subjects" }), ". Manual override is available."] }), (0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("span", { className: "font-semibold", children: "3. Preview & Validate:" }), " Review detected students, fix validation errors (missing names, duplicate rolls, out-of-range marks)."] }), (0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("span", { className: "font-semibold", children: "4. Generate:" }), " Pick validated students and generate one PDF per student. All reports are bundled into one ZIP."] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "card", children: [(0, jsx_runtime_1.jsx)("div", { className: "card-header", children: (0, jsx_runtime_1.jsx)("h3", { className: "font-semibold text-ink-900", children: "Sample Excel Format" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "card-body text-xs text-ink-700 overflow-x-auto", children: [(0, jsx_runtime_1.jsxs)("table", { className: "w-full whitespace-nowrap", children: [(0, jsx_runtime_1.jsx)("thead", { children: (0, jsx_runtime_1.jsx)("tr", { className: "border-b border-slate-200", children: ['Roll', 'Name', 'Class', 'Section', 'English', 'Maths', 'Science', 'Attendance'].map((c) => ((0, jsx_runtime_1.jsx)("th", { className: "text-left py-1.5 pr-3 font-semibold text-ink-800", children: c }, c))) }) }), (0, jsx_runtime_1.jsx)("tbody", { children: [
                                                    ['01', 'Aarav Sharma', '8', 'A', '92', '88', '95', '96%'],
                                                    ['02', 'Ananya Singh', '8', 'A', '95', 'AB', '90', '92%'],
                                                    ['03', 'Riya Verma', '8', 'A', '78', '82', 'EX', '89%'],
                                                ].map((r, i) => ((0, jsx_runtime_1.jsx)("tr", { className: "border-b border-slate-100", children: r.map((c, j) => ((0, jsx_runtime_1.jsx)("td", { className: "py-1.5 pr-3", children: c }, j))) }, i))) })] }), (0, jsx_runtime_1.jsx)("p", { className: "mt-3 text-ink-500", children: "Subjects are NOT hard-coded. Add any subjects \u2014 Science, Sanskrit, GK, IT \u2014 they are detected and mapped automatically." })] })] })] })] }));
}
function StatCard({ label, value, sub, tone, }) {
    const toneCls = {
        brand: 'text-brand-700',
        success: 'text-emerald-700',
        error: 'text-red-700',
        neutral: 'text-ink-800',
    }[tone];
    return ((0, jsx_runtime_1.jsx)("div", { className: "card", children: (0, jsx_runtime_1.jsxs)("div", { className: "card-body", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-xs font-semibold uppercase tracking-wide text-ink-500", children: label }), (0, jsx_runtime_1.jsx)("div", { className: `text-2xl font-bold mt-1 ${toneCls}`, children: value }), sub && (0, jsx_runtime_1.jsx)("div", { className: "text-xs text-ink-500 mt-1 line-clamp-2", children: sub })] }) }));
}
